In [2]:
import pandas as pd

data_geo = pd.read_csv(r"C:\Users\mariu\Downloads\ip_geo\IP2LOCATION-LITE-DB9.CSV")
data_geo

,0,16777215,-,-.1,-.2,-.3,0.000000,0.000000.1,-.4
0,16777216,16777471,US,United States of America,California,Los Angeles,34.052230,-118.24368,90001
1,16777472,16778239,CN,China,Fujian,Fuzhou,26.061390,119.30611,350004
2,16778240,16779263,AU,Australia,Victoria,Melbourne,-37.814000,144.96332,8010
3,16779264,16781311,CN,China,Guangdong,Guangzhou,23.116670,113.25000,510140
4,16781312,16785407,JP,Japan,Tokyo,Tokyo,35.689506,139.69170,160-0021
...,...,...,...,...,...,...,...,...,...
2906336,3758094336,3758095359,HK,Hong Kong,Hong Kong,Hong Kong,22.285520,114.15769,-
2906337,3758095360,3758095871,CN,China,Fujian,Fuzhou,26.061390,119.30611,350004
2906338,3758095872,3758096127,SG,Singapore,Singapore,Singapore,1.289670,103.85007,179431
2906339,3758096128,3758096383,AU,Australia,Queensland,Brisbane,-27.467940,153.02809,4000
2906340,3758096384,4294967295,-,-,-,-,0.000000,0.00000,-

In [121]:
data_ger = data_geo[data_geo.iloc[:,3]== 'Germany']

In [122]:
data_nrw = data_ger[data_ger.iloc[:,4]== 'Nordrhein-Westfalen']

In [123]:
data_nrw['Latitude'] = data_nrw.iloc[:, 6]
data_nrw['Longitude'] = data_nrw.iloc[:, 7]
data_nrw_2 = data_nrw.iloc[:,2:8].drop_duplicates()
data_nrw_2.to_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\geo_mun.csv", index=False)

C:\Users\mariu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\mariu\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [124]:
import geopandas as gp
from geopy.geocoders import Nominatim
import time

df_hist = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\nrw_hist_core_2.csv",error_bad_lines=False, sep=';')
df_hist

,Stimmen,Name,Partei,Wahlbezirk,test,test_1,test_2,Wahlbezirk ID,Stadt,Incumbent,Wahlbezirk_ID
0,39800.0,Graber,CDU,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,1,1.0
1,22800.0,KÃ¼hl,SPD,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,0,1.0
2,10400.0,Link-Schnitzler,GRÃœNE,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,0,1.0
3,5500.0,Zachel,FDP,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,1,1.0
4,3600.0,Kraft,UWG Kaarst,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
29386,3810.0,Glauner,WfW,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,1,33.0
29387,170.0,Lorani,REP,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,33.0
29388,700.0,Dahlmann,PRO NRW,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,33.0
29389,800.0,Mokry,PIRATEN,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,33.0
29390,1640.0,SchÃ¤fer,AfD,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,33.0

In [127]:
columns = ['test', 'test_1', 'test_2']

for i in range(2):
    
    col = columns[i]
    df_hist[col].str.replace(r'([\s][Nord])', '')
    df_hist[col].str.replace(r'([\s][West])', '')
    df_hist[col].str.replace(r'([\s][Mitte])', '')
    df_hist[col].str.replace(r'([\s][Ost])', '')
    df_hist[col].str.replace(r'([\s][SÃ¼d])', '')
    df_hist[col].str.replace(r'([\s][Sued])', '')
    df_hist[col].str.replace(r'([\s][W B])', '')
    df_hist[col].str.replace(r'([\s][links])', '')
    df_hist[col].str.replace(r'([\s][rechts])', '')
    df_hist[col].str.replace(r'([\s][Links])', '')
    df_hist[col].str.replace(r'([\s][Rechts])', '')
    df_hist[col].str.replace(r'([\s][V])$', '')
    df_hist[col].str.replace(r'([\s][I])$', '')

df_hist

,Stimmen,Name,Partei,Wahlbezirk,test,test_1,test_2,Wahlbezirk ID,Stadt,Incumbent,Wahlbezirk_ID
0,39800.0,Graber,CDU,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,1,1.0
1,22800.0,KÃ¼hl,SPD,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,0,1.0
2,10400.0,Link-Schnitzler,GRÃœNE,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,0,1.0
3,5500.0,Zachel,FDP,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,1,1.0
4,3600.0,Kraft,UWG Kaarst,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
29386,3810.0,Glauner,WfW,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,1,33.0
29387,170.0,Lorani,REP,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,33.0
29388,700.0,Dahlmann,PRO NRW,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,33.0
29389,800.0,Mokry,PIRATEN,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,33.0
29390,1640.0,SchÃ¤fer,AfD,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,33.0

In [168]:
df_hist['geopandas'] = df_hist['Wahlbezirk'] + ' ' + df_hist['Stadt']
df_hist['geopandas']

0        Flachsbleiche Sperberstr Kaarst
1        Flachsbleiche Sperberstr Kaarst
2        Flachsbleiche Sperberstr Kaarst
3        Flachsbleiche Sperberstr Kaarst
4        Flachsbleiche Sperberstr Kaarst
                      ...
29386            Ronsdorf West Wuppertal
29387            Ronsdorf West Wuppertal
29388            Ronsdorf West Wuppertal
29389            Ronsdorf West Wuppertal
29390            Ronsdorf West Wuppertal
Name: geopandas, Length: 29391, dtype: object

In [241]:
data_bz =  df_hist.groupby('geopandas', as_index = False).count()
from geopy.extra.rate_limiter import RateLimiter

# 1 - conveneint function to delay between geocoding calls
geocode = RateLimiter(locator.geocode, min_delay_seconds=1)

data_bz['location'] = data_bz['geopandas'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
data_bz['point'] = data_bz['location'].apply(lambda loc: tuple(loc.point) if loc else None)

KeyError: 'geopandas'

In [170]:
data_bz[['latitude', 'longitude', 'altitude']] = pd.DataFrame(data_bz['point'].tolist(), index=data_bz.index)

In [172]:
data_bz

,geopandas,Stimmen,Name,Partei,Wahlbezirk,test,test_1,test_2,Wahlbezirk ID,Stadt,Incumbent,Wahlbezirk_ID,location,point,latitude,longitude,altitude
0,Anhoven Wegberg,6,6,6,6,6,0,0,6,6,6,6,"(Rath-Anhoven, Kreis Heinsberg, Nordrhein-West...","(51.1110648, 6.3324303, 0.0)",51.111065,6.332430,0.0
1,Biesterberg Lemgo,7,7,7,7,7,0,0,7,7,7,7,"(Biesterberg, Lemgo, Kreis Lippe, Nordrhein-We...","(52.0079152, 8.8898027, 0.0)",52.007915,8.889803,0.0
2,Elbrachtschule SchloÃŸ Holte-Stukenbrock,10,10,10,10,10,0,0,10,10,10,10,None,None,NaN,NaN,NaN
3,Ergste I Schwerte,6,6,6,6,6,0,0,6,6,6,6,"(Ergste, Schwerte, Kreis Unna, Nordrhein-Westf...","(51.4161952, 7.5712974, 0.0)",51.416195,7.571297,0.0
4,Ergste Schwerte,12,12,12,12,12,0,0,12,12,12,12,"(Ergste, Schwerte, Kreis Unna, Nordrhein-Westf...","(51.4161952, 7.5712974, 0.0)",51.416195,7.571297,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3169,suedwestl und suedoest Stadtgebiet WipperfÃ¼rth,6,6,6,6,0,0,0,6,6,6,6,None,None,NaN,NaN,NaN
3170,Ã„uÃŸere Nordstadt Bonn,10,10,10,10,0,0,0,10,10,10,10,None,None,NaN,NaN,NaN
3171,Ã–strich/ Hardt Dorsten,6,6,6,6,0,0,0,6,6,6,6,"(Dorsten, A 31, Hardt, Dorsten, Kreis Reckling...","(51.6534746, 6.9299046, 0.0)",51.653475,6.929905,0.0
3172,Ãœberruhr Essen,13,13,13,13,0,0,0,13,13,13,13,"(Ãœberruhr-Holthausen, Stadtbezirk VIII, Essen,...","(51.4201134, 7.0796687, 0.0)",51.420113,7.079669,0.0
3173,Ãœlpenich ZÃ¼lpich,7,7,7,7,0,0,0,7,7,7,7,"(Ãœlpenich, ZÃ¼lpich, Kreis Euskirchen, Nordrhei...","(50.6752697, 6.6939097, 0.0)",50.675270,6.693910,0.0

In [173]:
df_hist_2 = pd.merge(df_hist, data_bz, on="geopandas", how="inner", validate="m:1")
df_hist_2

,Stimmen_x,Name_x,Partei_x,Wahlbezirk_x,test_x,test_1_x,test_2_x,Wahlbezirk ID_x,Stadt_x,Incumbent_x,...,test_2_y,Wahlbezirk ID_y,Stadt_y,Incumbent_y,Wahlbezirk_ID_y,location,point,latitude,longitude,altitude
0,39800.0,Graber,CDU,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,1,...,0,9,9,9,9,None,None,NaN,NaN,NaN
1,22800.0,KÃ¼hl,SPD,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,0,...,0,9,9,9,9,None,None,NaN,NaN,NaN
2,10400.0,Link-Schnitzler,GRÃœNE,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,0,...,0,9,9,9,9,None,None,NaN,NaN,NaN
3,5500.0,Zachel,FDP,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,1,...,0,9,9,9,9,None,None,NaN,NaN,NaN
4,3600.0,Kraft,UWG Kaarst,Flachsbleiche Sperberstr,NaN,NaN,NaN,1.0,Kaarst,0,...,0,9,9,9,9,None,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26614,3810.0,Glauner,WfW,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,1,...,0,10,10,10,10,"(Ronsdorf, Wuppertal, Nordrhein-Westfalen, 423...","(51.2264266, 7.1988387, 0.0)",51.226427,7.198839,0.0
26615,170.0,Lorani,REP,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,...,0,10,10,10,10,"(Ronsdorf, Wuppertal, Nordrhein-Westfalen, 423...","(51.2264266, 7.1988387, 0.0)",51.226427,7.198839,0.0
26616,700.0,Dahlmann,PRO NRW,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,...,0,10,10,10,10,"(Ronsdorf, Wuppertal, Nordrhein-Westfalen, 423...","(51.2264266, 7.1988387, 0.0)",51.226427,7.198839,0.0
26617,800.0,Mokry,PIRATEN,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,...,0,10,10,10,10,"(Ronsdorf, Wuppertal, Nordrhein-Westfalen, 423...","(51.2264266, 7.1988387, 0.0)",51.226427,7.198839,0.0
26618,1640.0,SchÃ¤fer,AfD,Ronsdorf West,NaN,NaN,NaN,33.0,Wuppertal,0,...,0,10,10,10,10,"(Ronsdorf, Wuppertal, Nordrhein-Westfalen, 423...","(51.2264266, 7.1988387, 0.0)",51.226427,7.198839,0.0

In [174]:
df_hist_2.to_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\geo_wb.csv",df_hist_2lse)

In [134]:
df_hist_2.loc[df_hist_2['location'].str.contains()]

In [162]:
df_hist_2.location.str.split(",", expand=True)

        0
0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
...    ..
26614 NaN
26615 NaN
26616 NaN
26617 NaN
26618 NaN

[26619 rows x 1 columns]

In [167]:
df_hist_2['location'].unique()

TypeError: unhashable type: 'Location'

In [183]:
df_stud = pd.read_csv(r"C:\Users\mariu\Downloads\students.csv", error_bad_lines=False, sep=';', engine = 'python')
df_stud

     Jahr             Stadt  student
0    2020              KÃ¶ln      602
1    2020  Bielefeld-Bethel      820
2    2020    Duisburg-Essen    42910
3    2020         Paderborn    20265
4    2020            Siegen    19457
..    ...               ...      ...
246  2014              MÃ¼ns       98
247  2014              Wese       60
248  2014    Sankt Augustin     4698
249  2014         Rheinbach     2009
250  2014            Hennef      327

[251 rows x 3 columns]

In [185]:
df_stud_2 = df_stud.groupby(['Jahr', 'Stadt'], as_index=False).sum()
df_stud_2.to_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\students.csv", index=False)

In [242]:
#df_uni_2 = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\unis.csv", error_bad_lines=False, sep=';')

# 1 - conveneint function to delay between geocoding calls
geocode = RateLimiter(locator.geocode, min_delay_seconds=1)

df_kand_extra['location'] = df_kand_extra['geopandas'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
df_kand_extra['point'] = df_kand_extra['location'].apply(lambda loc: tuple(loc.point) if loc else None)

df_kand_extra

ValueError: Columns must be same length as key

In [245]:
df_kand_extra[['latitude', 'longitude']] = pd.DataFrame(df_kand_extra['point'].tolist(), index=df_kand_extra.index)

ValueError: Columns must be same length as key

In [246]:
df_kand_extra['point'].tolist()

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.93732845, 6.959234323073302, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.87875, 6.981804397809072, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9359354, 6.871246459161802, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.9679925, 6.887914431752257, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (50.98864895, 6.935727475616647, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (51.03537, 6.892049121238911, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.8799229, 7.0950744704864315, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),
 (50.93596865, 7.066924990481073, 0.0),

In [211]:
df_prison = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\prisons.csv", error_bad_lines=False, sep=';')
df_prison = df_prison.dropna(thresh = 2).reset_index()
df_prison['location'] = df_prison['Addrese'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
df_prison['point'] = df_uni_2['location'].apply(lambda loc: tuple(loc.point) if loc else None)
df_prison[['latitude', 'longitude', 'altitude']] = pd.DataFrame(df_prison['point'].tolist(), index=df_prison.index)

df_prison

,index,Stadt,Addrese,location,point,latitude,longitude,altitude
0,0,Wuppertal,"Am Schmalenhof 6, 42369 Wuppertal","(JVA Wuppertal-Ronsdorf, 6, Am Schmalenhof, Lo...","(52.1758856, 10.5483417644312, 0.0)",52.175886,10.548342,0.0
1,4,Willich,"GartenstraÃŸe 2, 47877 Willich","(2, GartenstraÃŸe, DarderhÃ¶fe, Willich, Kreis V...","(50.76398775, 6.079943564049829, 0.0)",50.763988,6.079944,0.0
2,8,Willich,"GartenstraÃŸe 26, 47877 Willich","(26, GartenstraÃŸe, DarderhÃ¶fe, Willich, Kreis ...","(50.779170300000004, 6.068920799008829, 0.0)",50.779170,6.068921,0.0
3,12,Willich,"GartenstraÃŸe 1, 47877 Willich","(1, GartenstraÃŸe, DarderhÃ¶fe, Willich, Kreis V...",None,NaN,NaN,NaN
4,16,Werl,"Belgische Str. 4, 59457 Werl","(Justizvollzugsanstalt Werl, 4, Belgische Stra...","(50.5622404, 6.7666161, 0.0)",50.562240,6.766616,0.0
5,20,Werther,"Theenhausener StraÃŸe 5, 33824 Werther","(Justizvollzugsanstalt, 5, Theenhausener StraÃŸ...","(52.0444503, 8.4927471671855, 0.0)",52.044450,8.492747,0.0
6,24,Westkirchen,"Hoetmarer StraÃŸe 37, 59320 Westkirchen","(Hoetmarer StraÃŸe, VoÃŸmar, Ennigerloh, Kreis W...","(52.010124399999995, 8.52524062229632, 0.0)",52.010124,8.525241,0.0
7,28,Verl,"Dalkeweg 29, 33415 Verl","(29, Dalkeweg, SÃ¼renheide, Verl, Kreis GÃ¼tersl...",None,NaN,NaN,NaN
8,32,Steinhagen,"Sandforther StraÃŸe 72, 33803 Steinhagen","(72, Sandforther StraÃŸe, Steinhagen, Kreis GÃ¼t...","(52.0376885, 8.493223283579532, 0.0)",52.037689,8.493223,0.0
9,36,Steinhagen,"Brockhagener StraÃŸe 55, 33803 Steinhagen","(55, Brockhagener StraÃŸe, JVA, Obersteinhagen,...","(51.45211235, 7.2099876164752, 0.0)",51.452112,7.209988,0.0
10,40,Siegburg,"LuisenstraÃŸe 90, 53721 Siegburg","(LuisenstraÃŸe, Siegburg, BrÃ¼ckberg, Siegburg, ...","(51.4739287, 7.252831032163131, 0.0)",51.473929,7.252831,0.0
11,44,Schwerte,"GillstraÃŸe 1, 58239 Schwerte","(JVA Schwerte, 1, GillstraÃŸe, Ergste, Schwerte...","(51.44703665, 7.27240841043452, 0.0)",51.447037,7.272408,0.0
12,48,Sassenberg,"GrÃ¶blingen 65, 48336 Sassenberg","(65, GrÃ¶blingen, Sassenberg, Kreis Warendorf, ...","(51.44712, 7.2448018, 0.0)",51.447120,7.244802,0.0
13,52,Remscheid,"MasurenstraÃŸe 28, 42899 Remscheid","(Justizvollzugsanstalt Remscheid, 28, Masurens...","(51.444157649999994, 7.2609654130607835, 0.0)",51.444158,7.260965,0.0
14,56,Rheinbach,"Aachener StraÃŸe 47, 53359 Rheinbach","(Aachener StraÃŸe, Oberdrees, Rheinbach, Rhein-...","(51.4880422, 7.212469035224654, 0.0)",51.488042,7.212469,0.0
15,60,Remscheid,"MasurenstraÃŸe 27, 42899 Remscheid",(PfortengebÃ¤ude Haus 1 JVA Remscheid Zweiganst...,"(50.720896550000006, 7.112960536643291, 0.0)",50.720897,7.112961,0.0
16,64,Ratingen,"Oberhausener StraÃŸe 30, 40472 Ratingen","(Oberhausener StraÃŸe, Rath, Stadtbezirk 6, Rat...","(50.7338124, 7.1022465, 0.0)",50.733812,7.102246,0.0
17,68,Oelde,"WiedenbrÃ¼cker StraÃŸe 9, 59302 Oelde","(9, WiedenbrÃ¼cker StraÃŸe, Keitlinghausen, Oeld...","(50.7800748, 7.182238035560475, 0.0)",50.780075,7.182238,0.0
18,72,MÃ¼nster,"GartenstraÃŸe 26, 48147 MÃ¼nster","(KÃ¼che/Kammer, 26, GartenstraÃŸe, Schlachthof, ...","(50.83406105, 6.905471017946898, 0.0)",50.834061,6.905471,0.0
19,75,Moers,"Luiter Strasse , 47447 Moers","(Luiter StraÃŸe, Achterathsheide, Kapellen, Moe...","(50.832105150000004, 6.880562044694122, 0.0)",50.832105,6.880562,0.0
20,81,MÃ¶nchengladbach,"ScharnhorststraÃŸe 1, 41063 MÃ¶nchengladbach","(1, ScharnhorststraÃŸe, Eicken, MÃ¶nchengladbach...","(51.930898, 8.876208, 0.0)",51.930898,8.876208,0.0
21,85,Krefeld,"NordstraÃŸe 158, 47798 Krefeld","(Haft- und Untersuchungsanstalt, 158, Nordstra...","(51.5060586, 7.456920484582625, 0.0)",51.506059,7.456920,0.0
22,89,KÃ¶ln,"Rochusstr. 350, 50827 KÃ¶ln","(350, RochusstraÃŸe, Am Butzweilerhof, Ossendor...","(51.489050950000006, 7.40627932790408, 0.0)",51.489051,7.406279,0.0
23,93,KÃ¶ln,"Rochusstr. 246, 50827 KÃ¶ln","(246, RochusstraÃŸe, Am Butzweilerhof, Ossendor...","(51.49148675, 7.412253733621737, 0.0)",51.491487,7.412254,0.0
24,97,Kleve,"Krohnestr. 11, 47533 Kleve","(JVA Kleve, 11, KrohnestraÃŸe, Oberstadt, Kleve...","(51.46408285, 7.005838648601001, 0.0)",51.464083,7.005839,0.0
25,101,Iserlohn,"Heidstr. 41, 58640 Iserlohn",None,"(51.248265450000005, 6.7912273130431355, 0.0)",51.248265,6.791227,0.0
26,105,HÃ¶velhof,"StaumÃ¼hler StraÃŸe 284, 33161 HÃ¶velhof","(JVA-HÃ¶velhof, 284, StaumÃ¼hler StraÃŸe, StaumÃ¼h...",None,NaN,NaN,NaN
27,109,Herford,"EimterstraÃŸe 15, 32049 Herford","(15, EimterstraÃŸe, Stiftberg, Herford-Stadt, K...","(51.19077325, 6.793516713552313, 0.0)",51.190773,6.793517,0.0
28,113,Herzebrock,"Pixeler StraÃŸe 3, 33442 Herzebrock","(3, Pixeler StraÃŸe, Herzebrock, Herzebrock-Cla...",None,NaN,NaN,NaN
29,117,HerzebrockClarholz,"HolzhofstraÃŸe 27, 33442 Herzebrock-Clarholz","(JVA Bielefeld-Senne - AuÃŸenstelle Clarholz, 2...","(51.2306993, 6.7740367436067555, 0.0)",51.230699,6.774037,0.0
30,121,Heinsberg,"Wichernstr. 5, 52525 Heinsberg","(Justizvollzugsanstalt Heinsberg, 5, Wichernst...","(51.242461500000005, 6.772218715233939, 0.0)",51.242462,6.772219,0.0
31,126,Hamm,"Bismarckstr. 5, 59065 Hamm","(JVA Hamm, 5, BismarckstraÃŸe, Berge, Hamm, Nor...","(51.38755255, 7.004470824271211, 0.0)",51.387553,7.004471,0.0
32,130,GÃ¼tersloh,"PavenstÃ¤dter Weg 233, 33334 GÃ¼tersloh (0 52 41...",None,"(51.39055125, 7.077688695995038, 0.0)",51.390551,7.077689,0.0
33,134,GÃ¼tersloh,"BahnhofstraÃŸe 79, 33397 Rietberg","(79, BahnhofstraÃŸe, Rietberg, Kreis GÃ¼tersloh,...",None,NaN,NaN,NaN
34,138,Hagen,"GerichtsstraÃŸe 5, 58097 Hagen","(5, GerichtsstraÃŸe, Hochschulviertel, Hagen-Mi...","(51.5137555, 7.118403532523521, 0.0)",51.513756,7.118404,0.0
35,142,Gelsenkirchen,"AldenhofstraÃŸe 99 - 101, 45883 Gelsenkirchen","(AldenhofstraÃŸe, Feldmark, Gelsenkirchen-Mitte...","(51.5751037, 7.030072707025771, 0.0)",51.575104,7.030073,0.0
36,148,Geldern,"MÃ¶hlendyck 50, 47608 Geldern","(50, MÃ¶hlendyck, An Zanderskath, Pont, Geldern...","(51.3771294, 7.495154028855863, 0.0)",51.377129,7.495154,0.0
37,152,FrÃ¶ndenberg,"Hirschberg 9, 58730 FrÃ¶ndenberg",None,"(51.683026, 7.8410803, 0.0)",51.683026,7.841080,0.0
38,156,Essen,"KrawehlstraÃŸe 59, 45130 Essen","(Justizvollzugsanstalt Essen, 59, KrawehlstraÃŸ...","(51.678627, 7.8111523, 0.0)",51.678627,7.811152,0.0
39,160,Euskirchen,"KÃ¶lner Str. 250, 53879 Euskirchen",(Begleitete RÃœCKfÃ¼hrung Euskirchen-Erlenhof e....,None,NaN,NaN,NaN
40,164,Duisburg,"GoethestraÃŸe 3, 47166 Duisburg","(3, GoethestraÃŸe, Dichterviertel, Hamborn, Dui...","(51.3773961, 7.696310374520884, 0.0)",51.377396,7.696310,0.0
41,168,Dinslaken,"BismarckstraÃŸe 47, 46535 Dinslaken",(Justizvollzugsanstalt Duisburg-Hamborn - Zwei...,None,NaN,NaN,NaN
42,174,Dortmund,"LÃ¼becker StraÃŸe 21, 44135 Dortmund","(JVA Dortmund, 21, LÃ¼becker StraÃŸe, Kaiserstra...","(50.928038900000004, 6.9281744676751575, 0.0)",50.928039,6.928174,0.0
43,178,Detmold,"Bielefelder StraÃŸe 78, 32756 Detmold","(Justizvollzugsanstalt Detmold, 78, Bielefelde...","(50.9351035, 6.8697729, 0.0)",50.935103,6.869773,0.0
44,182,DelbrÃ¼ck-Boke,"RÃ¶merweg 22, 33129 DelbrÃ¼ck-Boke","(22, RÃ¶merweg, Boke, DelbrÃ¼ck, Kreis Paderborn...","(50.93399125, 6.9889532761131274, 0.0)",50.933991,6.988953,0.0
45,186,DelbrÃ¼ck-Hagen,"Nordhagener StraÃŸe 52, 33129 DelbrÃ¼ck-Hagen","(52, Nordhagener StraÃŸe, Hagen, DelbrÃ¼ck, Krei...","(50.94780725, 6.961067812482962, 0.0)",50.947807,6.961068,0.0
46,190,DelbrÃ¼ck-,"WeststraÃŸe 16, 33129 DelbrÃ¼ck-Steinhorst",None,None,NaN,NaN,NaN
47,194,Coesfeld,"Borkener Str. 3, 48653 Coesfeld","(3, Borkener StraÃŸe, Goxel, Coesfeld, Kreis Co...","(50.9340419, 6.962102196257449, 0.0)",50.934042,6.962102,0.0
48,197,Castrop-Rauxel,"LerchenstraÃŸe 81, 44581 Castrop-Rauxel","(Justizvollzugsanstalt Castrop-Rauxel, 81, Ler...","(50.928038900000004, 6.9281744676751575, 0.0)",50.928039,6.928174,0.0
49,201,Bochum,"KrÃ¼mmede 3, 44712 Bochum","(Justizvollzugsanstalt Bochum, 3, KrÃ¼mmede, In...","(50.9517094, 6.900134036208486, 0.0)",50.951709,6.900134,0.0
50,205,Bochum-,LÃ¼tgendortmunder Hellweg 212,"(212, LÃ¼tgendortmunder Hellweg, Somborn, Lange...","(52.0171086, 8.9070016, 0.0)",52.017109,8.907002,0.0
51,206,Langendreer,(02 34) 2 39 09 - 0 / Fax: (02 34) 2 39 09 - ...,None,None,NaN,NaN,NaN
52,209,Bielefeld,"Senner StraÃŸe 250, 33659 Bielefeld","(Justizvollzugsanstalt Bielefeld - Senne, 250,...","(51.8975341, 7.644898895995588, 0.0)",51.897534,7.644899,0.0
53,213,Bielefeld,"ZinnstraÃŸe 33, 33649 Bielefeld","(33, ZinnstraÃŸe, Brackwede, Bielefeld, Nordrhe...","(51.9526384, 7.6417805, 0.0)",51.952638,7.641781,0.0
54,217,Bielefeld,"Umlostr. 100, 33649 Bielefeld","(Justizvollzugsanstalt Bielefeld - Brackwede, ...","(51.974656749999994, 7.601423517849765, 0.0)",51.974657,7.601424,0.0
55,221,Beckum,"Friedrichshorst 20, 59269 Beckum","(JVA, 20, Friedrichshorst, Gut Friedrichshorst...","(51.960044350000004, 7.647862466750001, 0.0)",51.960044,7.647862,0.0
56,225,Attendorn,"Biggeweg 5 - 7, 57439 Attendorn","(Biggeweg, Attendorn, Kreis Olpe, Nordrhein-We...","(51.96360715, 7.613135742994505, 0.0)",51.963607,7.613136,0.0
57,229,Aachen,"Krefelder StraÃŸe 251, 52070 Aachen","(Justizvollzugsanstalt Aachen, 251, Krefelder ...",None,NaN,NaN,NaN

In [212]:
df_prison.to_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\prisons.csv", index=False)

## Import all datasets

In [3]:
#df_marius = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\nrw_2020_marius_2.csv", error_bad_lines=False, sep=';')
#df_thomas = pd.read_csv(r"C:\Users\mariu\Downloads\complete.csv", error_bad_lines=False, sep=',') # no geo data needed
#df_thomas_bezirke = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\bezirke.csv", error_bad_lines=False, sep=';')
#df_geo_mun = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\geo_mun.csv", error_bad_lines=False, sep=',') #has geo_date
#df_students = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\students.csv", error_bad_lines=False, sep=',') #has geo_data
#df_prisons = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\prisons.csv", error_bad_lines=False, sep=',') # has geo_data#
df_controls = pd.read_csv(r"C:\Users\mariu\Downloads\demographics_nrw_2020.csv", error_bad_lines=False, sep=';', encoding='latin1') # no geo data needed

#df_hist = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\geo_wb.csv",error_bad_lines=False, sep=',') # has geo data
#df_mun_code = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\checklist_mun_2020_data.csv", error_bad_lines=False, sep=';') # no geo data needed
#url ='https://raw.githubusercontent.com/mariusgruenewald/local_election_predictions/master/data/NRW/protests_hist.csv'    
#df_protests_hist = pd.read_csv(url, error_bad_lines=False) # has geo data
#url_2 ='https://raw.githubusercontent.com/mariusgruenewald/local_election_predictions/master/data/NRW/2020/protests_2020.csv'
#df_protests_now = pd.read_csv(url_2, error_bad_lines=False) # has geo data
#df_kand_extra = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\kandidaten.csv", error_bad_lines=False, sep=';')
#df_edith = pd.read_csv(r"C:\Users\mariu\Downloads\kandidatenlisten_Edith.csv", error_bad_lines=False, sep=';')
#df_incumb = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw_mun_incumbent_now_2.csv", error_bad_lines=False, sep=';')

df_complete = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\test.csv", error_bad_lines=False, sep=';')

C:\Users\mariu\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (3,4,12,14,20,23,30,47) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## Get Geolocations and generate distance measures

In [360]:
df_kand_extra['geopandas'] = df_kand_extra['Wahlbezirk'] + ' ' + df_kand_extra['Stadt']
df_edith['geopandas'] = df_edith['Wahlbezirk'] + ' ' + df_edith['Stadt']
df_thomas_bezirke['geopandas'] = df_thomas_bezirke['Wahlbezirk'] + ' ' + df_thomas_bezirke['Stadt']

In [361]:
geocode = RateLimiter(locator.geocode, min_delay_seconds=1)

df_edith['location'] = df_edith['geopandas'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
df_edith['point'] = df_edith['location'].apply(lambda loc: tuple(loc.point) if loc else None)
df_edith[['latitude', 'longitude', 'altitude']] = pd.DataFrame(df_edith['point'].tolist(), index=df_edith.index)

df_edith

KeyboardInterrupt:

In [253]:
df_thomas_bezirke['location'] = df_thomas_bezirke['geopandas'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
df_thomas_bezirke['point'] = df_thomas_bezirke['location'].apply(lambda loc: tuple(loc.point) if loc else None)
#df_thomas_bezirke[['latitude', 'longitude', 'altitude']] = pd.DataFrame(df_thomas_bezirke['point'].tolist(), index=df_thomas_bezirke.index)

df_thomas_bezirke

,Column1,X,Wahlbezirk_Location,Wahlbezirk,Stadt,Wahlbezirk_ID,geopandas,location,point,latitude,longitude,altitude
0,87,792,1_Roetgen,Roetgen,Roetgen,1,Roetgen Roetgen,"(Roetgen, StÃ¤dteregion Aachen, Nordrhein-Westf...","(50.6471603, 6.1967728, 0.0)",50.647160,6.196773,0.0
1,88,797,2_Roetgen,Roetgen,Roetgen,2,Roetgen Roetgen,"(Roetgen, StÃ¤dteregion Aachen, Nordrhein-Westf...","(50.6471603, 6.1967728, 0.0)",50.647160,6.196773,0.0
2,89,802,3_Roetgen,Roetgen,Roetgen,3,Roetgen Roetgen,"(Roetgen, StÃ¤dteregion Aachen, Nordrhein-Westf...","(50.6471603, 6.1967728, 0.0)",50.647160,6.196773,0.0
3,90,807,4_Roetgen,Roetgen,Roetgen,4,Roetgen Roetgen,"(Roetgen, StÃ¤dteregion Aachen, Nordrhein-Westf...","(50.6471603, 6.1967728, 0.0)",50.647160,6.196773,0.0
4,91,812,5_Roetgen,Roetgen,Roetgen,5,Roetgen Roetgen,"(Roetgen, StÃ¤dteregion Aachen, Nordrhein-Westf...","(50.6471603, 6.1967728, 0.0)",50.647160,6.196773,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
472,1074,6731,Anne-Frank-Gymnasium,Anne-Frank-Gymnasium,Werne,15,Anne-Frank-Gymnasium Werne,"(Anne-Frank-Gymnasium, Johann-Gottfried-Herder...","(51.670292950000004, 7.617810091453719, 0.0)",51.670293,7.617810,0.0
473,1075,6737,Dorfgemeinschaftshaus Langern,Dorfgemeinschaftshaus Langern,Werne,16,Dorfgemeinschaftshaus Langern Werne,"(Dorfgemeinschaftshaus, LangernstraÃŸe, Lenklar...","(51.64554785, 7.558907214364641, 0.0)",51.645548,7.558907,0.0
474,1076,6743,Kindergarten St. Marien Horst,Kindergarten St. Marien Horst,Werne,17,Kindergarten St. Marien Horst Werne,None,None,NaN,NaN,NaN
475,1077,6749,Evangelisches Gemeindezentrum Stockum,Evangelisches Gemeindezentrum Stockum,Werne,18,Evangelisches Gemeindezentrum Stockum Werne,None,None,NaN,NaN,NaN
476,1078,6755,Kardinal-von-Galen-Schule,Kardinal-von-Galen-Schule,Werne,19,Kardinal-von-Galen-Schule Werne,"(Kardinal-von-Galen-Schule, KirchstraÃŸe, Stock...","(51.671596550000004, 7.700294264197223, 0.0)",51.671597,7.700294,0.0

In [254]:
df_kand_extra['location'] = df_kand_extra['geopandas'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
df_kand_extra['point'] = df_kand_extra['location'].apply(lambda loc: tuple(loc.point) if loc else None)
#df_kand_extra[['latitude', 'longitude', 'altitude']] = pd.DataFrame(df_kand_extra['point'].tolist(), index=df_kand_extra.index)

df_kand_extra

,Partei,Partei kurz,Wahlbezirk_ID,Name,Vorname,Geburtsjahr,Beruf,PLZ,Stadt,Wahlbezirk,...,_10,_11,_12,_13,geopandas,location,point,latitude,longitude,altitude
0,Klimaliste DÃ¼sseldorf,NaN,1.0,MÃ¼ller,Annette,1980.0,Theaterregisseurin,40233.0,DÃ¼sseldorf,Altstadt,...,NaN,NaN,NaN,NaN,Altstadt DÃ¼sseldorf,"(Altstadt DÃ¼sseldorf, A 46, Uedesheim, Neuss, ...","(51.1739016, 6.7754375, 0.0)",51.173902,6.775437,0.0
1,Alternative fÃ¼r Deutschland,AfD,1.0,Lanfermann,Rainer,1971.0,Wirtschaftsjurist,40474.0,DÃ¼sseldorf,Altstadt,...,NaN,NaN,NaN,NaN,Altstadt DÃ¼sseldorf,"(Altstadt DÃ¼sseldorf, A 46, Uedesheim, Neuss, ...","(51.1739016, 6.7754375, 0.0)",51.173902,6.775437,0.0
2,Christlich Demokratische Union Deutschlands,CDU,1.0,Hinkel,Josef,1959.0,BÃ¤cker,40213.0,DÃ¼sseldorf,Altstadt,...,NaN,NaN,NaN,NaN,Altstadt DÃ¼sseldorf,"(Altstadt DÃ¼sseldorf, A 46, Uedesheim, Neuss, ...","(51.1739016, 6.7754375, 0.0)",51.173902,6.775437,0.0
3,DIE LINKE,DIE LINKE,1.0,Klein,Peter,1956.0,Architekt,40211.0,DÃ¼sseldorf,Altstadt,...,NaN,NaN,NaN,NaN,Altstadt DÃ¼sseldorf,"(Altstadt DÃ¼sseldorf, A 46, Uedesheim, Neuss, ...","(51.1739016, 6.7754375, 0.0)",51.173902,6.775437,0.0
4,"Partei fÃ¼r Arbeit, Rechtsstaat, Tierschutz, El...",Die PARTEI,1.0,Hartmann,Sebastian,1981.0,Manager Kultur,40227.0,DÃ¼sseldorf,Altstadt,...,NaN,NaN,NaN,NaN,Altstadt DÃ¼sseldorf,"(Altstadt DÃ¼sseldorf, A 46, Uedesheim, Neuss, ...","(51.1739016, 6.7754375, 0.0)",51.173902,6.775437,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2293,Piratenpartei Deutschland (PIRATEN,NaN,33.0,Lindhorst,Annegret,1961.0,SelbststÃ¤ndige,NaN,MÃ¼nster,Nienberge,...,NaN,NaN,NaN,NaN,Nienberge MÃ¼nster,"(Nienberge, MÃ¼nster-West, MÃ¼nster, Nordrhein-W...","(51.9984211, 7.5595243, 0.0)",51.998421,7.559524,0.0
2294,Ã¶dp,NaN,33.0,Potzesny,Monika,1971.0,Physiotherapeutin,NaN,MÃ¼nster,Nienberge,...,NaN,NaN,NaN,NaN,Nienberge MÃ¼nster,"(Nienberge, MÃ¼nster-West, MÃ¼nster, Nordrhein-W...","(51.9984211, 7.5595243, 0.0)",51.998421,7.559524,0.0
2295,MÃ¼nster ist bunt und international (MBI,NaN,33.0,Below,Robert,1986.0,Student,NaN,MÃ¼nster,Nienberge,...,NaN,NaN,NaN,NaN,Nienberge MÃ¼nster,"(Nienberge, MÃ¼nster-West, MÃ¼nster, Nordrhein-W...","(51.9984211, 7.5595243, 0.0)",51.998421,7.559524,0.0
2296,"Partei fÃ¼r Arbeit, Rechtsstaat, Tierschutz, El...",NaN,33.0,BuÃŸ,Axel,1990.0,Physiker,NaN,MÃ¼nster,Nienberge,...,NaN,NaN,NaN,NaN,Nienberge MÃ¼nster,"(Nienberge, MÃ¼nster-West, MÃ¼nster, Nordrhein-W...","(51.9984211, 7.5595243, 0.0)",51.998421,7.559524,0.0
2297,Volt Deutschland (Volt+E344E359E348:E369,NaN,33.0,Dr. phil. Goldbeck,Markus,1984.0,GeschÃ¤ftsfÃ¼hrer,NaN,MÃ¼nster,Nienberge,...,NaN,NaN,NaN,NaN,Nienberge MÃ¼nster,"(Nienberge, MÃ¼nster-West, MÃ¼nster, Nordrhein-W...","(51.9984211, 7.5595243, 0.0)",51.998421,7.559524,0.0

In [255]:
df_marius['geopandas'] = df_marius['Wahlbezirk'] + ' ' + df_marius['Stadt']
df_marius['location'] = df_marius['geopandas'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
df_marius['point'] = df_marius['location'].apply(lambda loc: tuple(loc.point) if loc else None)
#df_kand_extra[['latitude', 'longitude', 'altitude']] = pd.DataFrame(df_kand_extra['point'].tolist(), index=df_kand_extra.index)

df_marius

,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei,Wahlbezirk,Wahlkreis_ID,Plz,Stadt,Nachname,Vorname,Wahlk_ID,Wahlbezirk2,geopandas,location,point
0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0,4513800.0,Essen,GrÃ¶ne,Jens-Peter,0,Stadtmitte,Stadtmitte Essen,"(Stadtmitte, A 52, Bergerhausen, Stadtbezirk I...","(51.457880450000005, 7.011603822069837, 0.0)"
1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0,4513900.0,Essen,Moos,Christiane,0,Stadtmitte,Stadtmitte Essen,"(Stadtmitte, A 52, Bergerhausen, Stadtbezirk I...","(51.457880450000005, 7.011603822069837, 0.0)"
2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0,4513100.0,Essen,Schumacher,Sandra,0,Stadtmitte,Stadtmitte Essen,"(Stadtmitte, A 52, Bergerhausen, Stadtbezirk I...","(51.457880450000005, 7.011603822069837, 0.0)"
3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0,4530700.0,Essen,El-Khatib,Jules,0,Stadtmitte,Stadtmitte Essen,"(Stadtmitte, A 52, Bergerhausen, Stadtbezirk I...","(51.457880450000005, 7.011603822069837, 0.0)"
4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0,4513400.0,Essen,Hemsteeg,Kai,0,Stadtmitte,Stadtmitte Essen,"(Stadtmitte, A 52, Bergerhausen, Stadtbezirk I...","(51.457880450000005, 7.011603822069837, 0.0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8332,40.0,"NiÃŸing, Andrea",Altenpflegerin,1957.0,DIE LINKE DIE LINKE,NaN,21,470380.0,Dinslaken,"NiÃŸing,",Andrea,21,NaN,NaN,"(Nanno, ComunitÃ della Val di Non, Provincia d...","(46.3144754, 11.0480288, 0.0)"
8333,50.0,"BrÃ¼cker, Heinz",NaN,1950.0,UBV,NaN,21,470410.0,Dinslaken,"BrÃ¼cker,",Heinz,21,NaN,NaN,"(Nanno, ComunitÃ della Val di Non, Provincia d...","(46.3144754, 11.0480288, 0.0)"
8334,60.0,"Strewginski, Niklas",NaN,1992.0,FDP,NaN,21,470440.0,Dinslaken,"Strewginski,",Niklas,21,NaN,NaN,"(Nanno, ComunitÃ della Val di Non, Provincia d...","(46.3144754, 11.0480288, 0.0)"
8335,70.0,"Topal, Levent",Schlosser,1974.0,AWG,NaN,21,470460.0,Dinslaken,"Topal,",Levent,21,NaN,NaN,"(Nanno, ComunitÃ della Val di Non, Provincia d...","(46.3144754, 11.0480288, 0.0)"
8336,80.0,"Weusthoff, Sven",Erzieher,1987.0,Die PARTEI,NaN,21,470480.0,Dinslaken,"Weusthoff,",Sven,21,NaN,NaN,"(Nanno, ComunitÃ della Val di Non, Provincia d...","(46.3144754, 11.0480288, 0.0)"

In [284]:
df_thomas['Stadt'] = df_thomas['Ort']
df_thomas_2 = pd.merge(df_thomas, df_thomas_bezirke, on=["Stadt", "Wahlbezirk_ID"], how="left", validate="m:m")
df_thomas_2['Wahlkreis_ID'] = df_thomas_2['Wahlbezirk_ID']

In [270]:
df_thomas_2.to_csv(r"C:\Users\mariu\Downloads\complete_2.csv")
df_edith.to_csv(r"C:\Users\mariu\Downloads\kandidatenlisten_Edith_2.csv")
df_kand_extra.to_csv(r"C:\Users\mariu\Documents\Project Local Elections\kandidaten_2.csv")
df_marius.to_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\nrw_2020_marius_3.csv")

## Combine predictors

In [313]:
df_hist['Jahr'] = 2014

In [314]:
data_2020 = df_marius.append(df_edith)
data_2020 = data_2020.append(df_kand_extra)
data_2020 = data_2020.append(df_thomas_2)
data_2020_2 = pd.merge(data_2020, df_incumb, how="left", on=["Stadt", "Nachname"], validate="m:m")
data_2020_2.loc[data_2020_2['mun_code'].astype(str) == 'nan', 'Incumbent'] = 0

In [315]:
data_2020_2['Jahr'] = 2020

In [370]:
df_hist = df_hist.rename(columns={"Stimmen_x": "Stimmen", "Name_x": "Nachname", "Partei_x": "Partei", "Wahlbezirk_x": "Wahlbezirk", "Wahlbezirk ID_x": "Wahlkreis_ID", "Stadt_x": "Stadt","Incumbent_x": "Incumbent"})

In [618]:
data_2020_1 = data_2020_2.append(df_hist).reset_index()

In [372]:
#data_2020_1.to_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\nrw_data_plausi.csv")

In [377]:
data_loca = pd.DataFrame()
data_loca['Stadt'] = data_2020_1['Stadt'].unique()
data_loca

              Stadt
0             Essen
1           Bedburg
2     Engelskirchen
3             Ahlen
4        Oberhausen
..              ...
262          Vlotho
263         Waltrop
264     Weilerswist
265  Wickede (Ruhr)
266     WipperfÃ¼rth

[267 rows x 1 columns]

In [381]:
data_loca['location_city'] = data_loca['Stadt'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
data_loca['point_city'] = data_loca['location_city'].apply(lambda loc: tuple(loc.point) if loc else None)
data_loca

,Stadt,location_city,point_city
0,Essen,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)"
1,Bedburg,"(Bedburg, Rhein-Erft-Kreis, Nordrhein-Westfale...","(50.9976706, 6.576634, 0.0)"
2,Engelskirchen,"(Engelskirchen, Oberbergischer Kreis, Nordrhei...","(50.9872964, 7.4084206, 0.0)"
3,Ahlen,"(Ahlen, Kreis Warendorf, Nordrhein-Westfalen, ...","(51.7627633, 7.8909086, 0.0)"
4,Oberhausen,"(Oberhausen, Nordrhein-Westfalen, Deutschland,...","(51.4696137, 6.8514435, 0.0)"
...,...,...,...
262,Vlotho,"(Vlotho, Kreis Herford, Nordrhein-Westfalen, 3...","(52.1664861, 8.8619172, 0.0)"
263,Waltrop,"(Waltrop, Kreis Recklinghausen, Nordrhein-West...","(51.6237456, 7.400959, 0.0)"
264,Weilerswist,"(Weilerswist, Kreis Euskirchen, Nordrhein-West...","(50.7580669, 6.8407873, 0.0)"
265,Wickede (Ruhr),"(Wickede (Ruhr), Kreis Soest, Nordrhein-Westfa...","(51.4960475, 7.8696034, 0.0)"
266,WipperfÃ¼rth,"(WipperfÃ¼rth, Oberbergischer Kreis, Nordrhein-...","(51.1155182, 7.3879068, 0.0)"

In [619]:
data_2020_1 = pd.merge(data_2020_1, data_loca, how="left", on="Stadt", validate="m:1").reset_index()
data_2020_1

,level_0,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei,Wahlbezirk,Wahlkreis_ID,Plz,...,Wahlbezirk_y,test_y,test_1_y,test_2_y,Wahlbezirk ID_y,Stadt_y,Incumbent_y,Wahlbezirk_ID_y,location_city,point_city
0,0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)"
1,1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)"
2,2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)"
3,3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)"
4,4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42748,42748,26614,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,...,10.0,0.0,0.0,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)"
42749,42749,26615,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,...,10.0,0.0,0.0,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)"
42750,42750,26616,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,...,10.0,0.0,0.0,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)"
42751,42751,26617,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,...,10.0,0.0,0.0,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)"
42752,42752,26618,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,...,10.0,0.0,0.0,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)"

In [640]:
from geopy.distance import geodesic
import numpy as np

data_2020_1.loc[data_2020_1['points'].astype(str) == 'nan', 'point'] = None

distance_1 = []
distance_1_index = []
for index, row in data_2020_1.iterrows():
    if index > 0:
        try:
            distance_1.append([geodesic(row['points'], row['point_city']).km, index])
            
        except ValueError:
            distance_1_index.append(index)

KeyError: 'points'

In [598]:
dis_2 =pd.DataFrame([distance_2], columns).T
dis_2.to_excel(r"C:\Users\mariu\Documents\Project Local Elections\distance_2.xlsx")

In [544]:
dis = pd.DataFrame([distance_1], columns).T
dis.to_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\distance.csv")

In [558]:
data_distance = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\distance.csv", sep=';')
data_distance['Distance'] = data_distance['Distance'].str.replace('[', '').astype(float)
data_distance['index'] = data_distance['Index']

In [561]:
data_2020_1 = data_2020_1.drop('index', axis=1).reset_index()
data_2020_3 = pd.merge(data_2020_1, data_distance, on="index", validate="1:1", how="outer")
data_2020_3

,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei,Wahlbezirk,Wahlkreis_ID,Plz,Stadt,...,test_2_y,Wahlbezirk ID_y,Stadt_y,Incumbent_y,Wahlbezirk_ID_y,location_city,point_city,Column1_y,Distance,Index
0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,Essen,...,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)",NaN,NaN,NaN
1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,Essen,...,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)",0.0,0.295317,1.0
2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,Essen,...,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)",1.0,0.295317,2.0
3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,Essen,...,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)",2.0,0.295317,3.0
4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,Essen,...,NaN,NaN,NaN,NaN,NaN,"(Essen, Nordrhein-Westfalen, Deutschland, (51....","(51.4582235, 7.0158171, 0.0)",3.0,0.295317,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42748,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,Wuppertal,...,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)",NaN,NaN,NaN
42749,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,Wuppertal,...,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)",NaN,NaN,NaN
42750,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,Wuppertal,...,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)",NaN,NaN,NaN
42751,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,Wuppertal,...,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)",NaN,NaN,NaN
42752,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,Wuppertal,...,0.0,10.0,10.0,10.0,10.0,"(Wuppertal, Nordrhein-Westfalen, Deutschland, ...","(51.264018, 7.1780374, 0.0)",NaN,NaN,NaN

In [588]:
df_controls = df_controls[df_controls['Mun_ID'] > 5000000]
data_2020_4 = pd.merge(data_2020_3, df_controls, how='left', on=['Stadt', 'Jahr'], validate="m:m")
data_2020_4

,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei,Wahlbezirk,Wahlkreis_ID,Plz,Stadt,...,employees,unemployed_tot,unemployed_foreign,unemployed_youth,unemployed_old,long_time_unemployed,tourist_arrivals,social_sec,filed_bancruptcies_firms,employees_beau
0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,Essen,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,Essen,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,Essen,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,Essen,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,Essen,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [593]:
data_2020_4.loc[(data_2020_4['Distance'].astype(str) == 'nan') | (data_2020_4['Distance'].astype(str) == 'None'), 'Distance'] = 0
data_2020_4[['Distance']]

       Distance
0      0.000000
1      0.295317
2      0.295317
3      0.295317
4      0.295317
...         ...
43074  0.000000
43075  0.000000
43076  0.000000
43077  0.000000
43078  0.000000

[43079 rows x 1 columns]

In [680]:
#data_2020_4.to_excel(r"C:\Users\mariu\Documents\Project Local Elections\nrw\test.xlsx")
data_2020_4 = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\test.csv", sep=";")

C:\Users\mariu\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (2,3,11,13,19,22,29) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [670]:
df_students['Uni'] = 'UniversitÃ¤t'
df_students['geopandas'] = df_students['Stadt'] + ' ' + df_students['Uni']

In [671]:
df_students['location_uni'] = df_students['geopandas'].apply(geocode)
# 3 - create longitude, laatitude and altitude from location column (returns tuple)
df_students['point_city'] = df_students['location_uni'].apply(lambda loc: tuple(loc.point) if loc else None)

In [672]:
df_students = df_students.rename(columns={'point_city': 'point_uni'})
df_students

,Jahr,Stadt,student,Uni,geopandas,location_uni,point_uni
0,2014,Aachen,50332,UniversitÃ¤t,Aachen UniversitÃ¤t,(FH Aachen: Allgemeiner Studierendenausschuss ...,"(50.769081, 6.0800356, 0.0)"
1,2014,Alfter,992,UniversitÃ¤t,Alfter UniversitÃ¤t,"(Alanus Hochschule Campus I, Lohheckenweg, Ols...","(50.73230985, 6.998785284613957, 0.0)"
2,2014,Bad MÃ¼nstereifel,680,UniversitÃ¤t,Bad MÃ¼nstereifel UniversitÃ¤t,None,None
3,2014,Bergisch-Gladbach,592,UniversitÃ¤t,Bergisch-Gladbach UniversitÃ¤t,"(b.i.b./FHDW GebÃ¤ude F, Refrather Weg, Duckter...","(50.98304375, 7.118078983964644, 0.0)"
4,2014,Bielefeld,33334,UniversitÃ¤t,Bielefeld UniversitÃ¤t,"(UniversitÃ¤t, Erfahrung, Gellershagen, Schilde...","(52.0391049, 8.4970672, 0.0)"
...,...,...,...,...,...,...,...
124,2020,Unna,300,UniversitÃ¤t,Unna UniversitÃ¤t,(DHGS Deutsche Hochschule fÃ¼r Gesundheit und S...,"(51.552109, 7.6369307, 0.0)"
125,2020,Velbert/Heiligenhaus,354,UniversitÃ¤t,Velbert/Heiligenhaus UniversitÃ¤t,"(Campus Velbert/Heiligenhaus, Campusallee, Vog...","(51.327619049999996, 6.967577695078486, 0.0)"
126,2020,Wese,312,UniversitÃ¤t,Wese UniversitÃ¤t,None,None
127,2020,Witten-Herdecke,2427,UniversitÃ¤t,Witten-Herdecke UniversitÃ¤t,"(UniversitÃ¤t Witten/Herdecke, 50, Alfred-Herrh...","(51.45226925, 7.357083802888063, 0.0)"
128,2020,Wuppertal,22776,UniversitÃ¤t,Wuppertal UniversitÃ¤t,"(UniversitÃ¤t, Wolfshahn, Gemarkung Elberfeld, ...","(51.2456378, 7.1500554, 0.0)"

In [675]:
df_prisons
df_prisons['geopandas'] = df_prisons['Stadt'] + 'Justizvollzugsanstalt'
df_prisons['location_prison'] = df_prisons['Addrese'].apply(geocode)
df_prisons['point_prison'] = df_prisons['location_prison'].apply(lambda loc: tuple(loc.point) if loc else None)

In [682]:
data_2020_5 = pd.merge(data_2020_4, df_students[['Jahr', 'Stadt', 'student', 'point_uni']], how="left", on=["Jahr", "Stadt"], validate="m:1")
data_2020_5

,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei,Wahlbezirk,Wahlkreis_ID,Plz,Stadt,...,Mun_ID,points.1,Unnamed: 33,point_city.1,Unnamed: 35,Unnamed: 36,Unnamed: 37,Distance_WB,student,point_uni
0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,Essen,...,5113000.0,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)"
1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,Essen,...,5113000.0,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)"
2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,Essen,...,5113000.0,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)"
3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,Essen,...,5113000.0,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)"
4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,Essen,...,5113000.0,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)"
43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)"
43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)"
43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)"
43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,Wuppertal,...,NaN,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)"

In [689]:
data_2020_6 = pd.merge(data_2020_5, df_prisons.drop([8, 3,2, 15,23,32,46, 50,53,54])[['Stadt', 'point_prison']], how="left", on=["Stadt"], validate="m:1")
data_2020_6

,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei,Wahlbezirk,Wahlkreis_ID,Plz,Stadt,...,points.1,Unnamed: 33,point_city.1,Unnamed: 35,Unnamed: 36,Unnamed: 37,Distance_WB,student,point_uni,point_prison
0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,Essen,...,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)"
1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,Essen,...,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)"
2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,Essen,...,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)"
3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,Essen,...,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)"
4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,Essen,...,"51,45788045","7,011603822","51,4582235","7,0158171","5,33809E-10","4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,Wuppertal,...,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)"
43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,Wuppertal,...,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)"
43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,Wuppertal,...,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)"
43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,Wuppertal,...,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)"
43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,Wuppertal,...,"51,2264266","7,1988387","51,264018","7,1780374","1,20527E-07","0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)"

In [694]:
df_protests_hist['Jahr'] = 2014
df_protests_now['Jahr'] = 2020
df_protest = df_protests_hist.append(df_protests_now)
df_protest['Stadt'] = df_protest['eventgeo_name'].str.split(',',expand=True)[0]
df_protest['Stadt'] = df_protest['Stadt'].str.replace('Koln', 'KÃ¶ln')
df_protest['Stadt'] = df_protest['Stadt'].str.replace('Konigswinter', 'KÃ¶nigswinter')
df_protest['Stadt'] = df_protest['Stadt'].str.replace('Gutersloh', 'GÃ¼tersloh')
df_protest

,Unnamed: 0,eventgeo_name,num_mentions,eventgeo_lat,eventgeo_long,avg_tone,count,Jahr,Stadt
0,0,"Bochum, Nordrhein-Westfalen, Germany",3.000000,51.4833,7.21667,3.432836,1,2014,Bochum
1,1,"Bonn, Nordrhein-Westfalen, Germany",4.529412,50.7333,7.10000,2.330657,17,2014,Bonn
2,2,"Koln, Nordrhein-Westfalen, Germany",12.250000,50.9333,6.95000,-0.311772,4,2014,KÃ¶ln
3,3,"Konigswinter, Nordrhein-Westfalen, Germany",6.000000,50.6833,7.18333,3.911205,1,2014,KÃ¶nigswinter
4,4,"Rheda, Nordrhein-Westfalen, Germany",10.000000,51.9833,8.20000,3.351955,1,2014,Rheda
5,5,"Solingen, Nordrhein-Westfalen, Germany",41.250000,51.1833,7.08333,3.387091,8,2014,Solingen
6,6,"Steinfurt, Nordrhein-Westfalen, Germany",6.000000,52.1500,7.35000,1.500000,1,2014,Steinfurt
0,0,"Bismarck, Nordrhein-Westfalen, Germany",3.500000,51.5500,7.10000,-2.949483,4,2020,Bismarck
1,1,"Bochum, Nordrhein-Westfalen, Germany",14.666667,51.4833,7.21667,-4.301591,3,2020,Bochum
2,2,"Bonn, Nordrhein-Westfalen, Germany",7.066667,50.7333,7.10000,-1.567228,15,2020,Bonn
3,3,"Bottrop, Nordrhein-Westfalen, Germany",5.000000,51.5167,6.91667,-1.872659,2,2020,Bottrop
4,4,"Datteln, Nordrhein-Westfalen, Germany",6.500000,51.6667,7.38333,-3.279144,6,2020,Datteln
5,5,"Dormagen, Nordrhein-Westfalen, Germany",2.500000,51.1000,6.83333,-2.292769,2,2020,Dormagen
6,6,"Eppendorf, Nordrhein-Westfalen, Germany",6.000000,51.4500,7.18333,-5.042335,4,2020,Eppendorf
7,7,"Gutersloh, Nordrhein-Westfalen, Germany",13.000000,51.9000,8.38333,-3.666553,2,2020,GÃ¼tersloh
8,8,"Haltern, Nordrhein-Westfalen, Germany",2.000000,52.1167,7.26667,-3.680253,1,2020,Haltern
9,9,"Heinsberg, Nordrhein-Westfalen, Germany",9.333333,51.0333,8.15000,-4.242424,3,2020,Heinsberg
10,10,"Krefeld, Nordrhein-Westfalen, Germany",5.000000,51.3333,6.56667,-4.740406,2,2020,Krefeld
11,11,"Marxloh, Nordrhein-Westfalen, Germany",5.000000,51.5167,6.76667,1.515152,2,2020,Marxloh
12,12,"Rheinberg, Nordrhein-Westfalen, Germany",10.000000,51.5500,6.60000,-3.416149,2,2020,Rheinberg
13,13,"Sankt Augustin, Nordrhein-Westfalen, Germany",15.000000,50.7667,7.18333,-3.914784,4,2020,Sankt Augustin
14,14,"Warendorf, Nordrhein-Westfalen, Germany",10.000000,51.9500,7.98333,-3.835798,3,2020,Warendorf
15,15,"Wuppertal, Nordrhein-Westfalen, Germany",10.000000,51.2667,7.18333,-0.604230,1,2020,Wuppertal

In [696]:
data_2020_7 = pd.merge(data_2020_6, df_protest[['Stadt', 'Jahr', 'num_mentions', 'count', 'avg_tone', 'eventgeo_lat', 'eventgeo_long']], on=["Stadt", "Jahr"], how="left", validate="m:1")

,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei,Wahlbezirk,Wahlkreis_ID,Plz,Stadt,...,Unnamed: 37,Distance_WB,student,point_uni,point_prison,num_mentions,count,avg_tone,eventgeo_lat,eventgeo_long
0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,Essen,...,"4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)",NaN,NaN,NaN,NaN,NaN
1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,Essen,...,"4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)",NaN,NaN,NaN,NaN,NaN
2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,Essen,...,"4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)",NaN,NaN,NaN,NaN,NaN
3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,Essen,...,"4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)",NaN,NaN,NaN,NaN,NaN
4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,Essen,...,"4,62086E-05","0,294395185",5975.0,"(51.4662094, 7.0018953233349155, 0.0)","(51.43834375, 6.99761448538213, 0.0)",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,Wuppertal,...,"0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)",NaN,NaN,NaN,NaN,NaN
43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,Wuppertal,...,"0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)",NaN,NaN,NaN,NaN,NaN
43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,Wuppertal,...,"0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)",NaN,NaN,NaN,NaN,NaN
43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,Wuppertal,...,"0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)",NaN,NaN,NaN,NaN,NaN
43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,Wuppertal,...,"0,00069434","4,423643207",19094.0,"(51.2456378, 7.1500554, 0.0)","(51.2418276, 7.218294302054558, 0.0)",NaN,NaN,NaN,NaN,NaN

In [698]:
data_2020_7.to_excel(r"C:\Users\mariu\Documents\Project Local Elections\nrw\test.xlsx")

In [4]:
data_complete = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\test.csv", sep=";")

In [5]:
data_complete.loc[data_complete['points'].astype(str) == 'nan', 'distance_uni'] = 0
data_complete.loc[data_complete['points'].astype(str) == 'nan', 'distance_prison'] = 0
data_complete

,Unnamed: 0,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei,Wahlbezirk,Wahlkreis_ID,Plz,...,distance_uni,point_prison,Unnamed: 44,Unnamed: 45,distance_prison,num_mentions,count,avg_tone,eventgeo_lat,eventgeo_long
0,0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,NaN,NaN,NaN
1,1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,NaN,NaN,NaN
2,2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,NaN,NaN,NaN
3,3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,NaN,NaN,NaN
4,4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43074,43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,NaN,NaN,NaN
43075,43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,NaN,NaN,NaN
43076,43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,NaN,NaN,NaN
43077,43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,NaN,NaN,NaN
43078,43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,NaN,NaN,NaN

In [6]:
data_complete.loc[data_complete['num_mentions'].astype(str) == '0', 'avg_tone'] = 0
data_complete

,Unnamed: 0,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei,Wahlbezirk,Wahlkreis_ID,Plz,...,distance_uni,point_prison,Unnamed: 44,Unnamed: 45,distance_prison,num_mentions,count,avg_tone,eventgeo_lat,eventgeo_long
0,0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,0,NaN,NaN
1,1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,0,NaN,NaN
2,2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,0,NaN,NaN
3,3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,0,NaN,NaN
4,4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,...,"0,001144597","51,43834375","6,997614485","3,48554E-08","20,01270791",0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43074,43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,0,NaN,NaN
43075,43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,0,NaN,NaN
43076,43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,0,NaN,NaN
43077,43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,0,NaN,NaN
43078,43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,...,"0,004012272","51,2418276","7,218294302","2,93644E-08","20,01290332",0,0,0,NaN,NaN

In [99]:
from bs4 import BeautifulSoup
import requests
from urllib.parse import quote
from time import sleep
import re
import random


def beautiful_soup(names, year, city):
    
    headers = {
    'User-Agent': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'
    }
    
    results_next = []
    new_core = []

    for i in range(len(names)):
            
        page_link = 'https://www.ecosia.org/search?q=' + names[i] + ' ' + str(year[i]) + ' '+ city[i]
            
        sleep(random.randint(5,16)) #Script will be stopped for a period of time ranging from 5 to 16 seconds.

        page_response = requests.get(page_link, headers = headers)

        page_content = BeautifulSoup(page_response.content, "html.parser")
        text = page_content.get_text()
        
        core = re.findall(r"\n\n\n\n\n\n\n\n\n\n\n(.*)", text)
        
        new_core.append(core[26])
        
        results_next.append([names[i], year[i], city[i], new_core[i]])
        
    data_google = pd.DataFrame(data=results_next, columns = ['Nachname', 'Jahr', 'Stadt', 'google'])
    
    return data_google

In [100]:
google_data= beautiful_soup(data_complete['Nachname'][0:5], data_complete['Jahr'][0:5], data_complete['Stadt'][0:5])
google_data

,Nachname,Jahr,Stadt,google
0,GrÃ¶ne,2020.0,Essen,GrÃ¶ne in Essen im Das Tele...
1,Moos,2020.0,Essen,Kokedera / Saihoji - der M...
2,Schumacher,2020.0,Essen,Einschulung in Stuhr und W...
3,El-Khatib,2020.0,Essen,Veranstaltungen Â· Ferienspatz
4,Hemsteeg,2020.0,Essen,Fraktionschef Kai Hemsteeg...

In [7]:
data_manifesto = pd.read_csv(r"C:\Users\mariu\Documents\Project Local Elections\manifesto.csv", sep=";")

data_complete.loc[data_complete['Partei'].str.contains('SPD') == True, 'Partei_kurz'] = 'SPD'
data_complete.loc[data_complete['Partei'].str.contains('CDU') == True, 'Partei_kurz'] = 'CDU'
data_complete.loc[data_complete['Partei'].str.contains('FDP') == True, 'Partei_kurz'] = 'FDP'
data_complete.loc[data_complete['Partei'].str.contains('GRÃœNE') == True, 'Partei_kurz'] = 'GrÃ¼ne'
data_complete.loc[data_complete['Partei'].str.contains('LINKE') == True, 'Partei_kurz'] = 'Linke'
data_complete.loc[data_complete['Partei'].str.contains('AfD') == True, 'Partei_kurz'] = 'AfD'
data_complete.loc[data_complete['Partei'].str.contains('PIRATEN') == True, 'Partei_kurz'] = 'Piraten'
data_complete.loc[data_complete['Partei'].str.contains('PARTEI') == True, 'Partei_kurz'] = 'Partei'
data_complete.loc[data_complete['Partei'].str.contains('Tierschutzpartei') == True, 'Partei_kurz'] = 'Tierschutzpartei'
data_complete.loc[data_complete['Partei'].str.contains('PARTEI MENSCH') == True, 'Partei_kurz'] = 'Tierschutzpartei'
data_complete.loc[data_complete['Partei'].str.contains('Volt') == True, 'Partei_kurz'] = 'Volt'
data_complete.loc[data_complete['Partei'].str.contains('Kommunistische') == True, 'Partei_kurz'] = 'DKP'
data_complete.loc[data_complete['Partei'].str.contains('Alternative fÃ¼r Deu') == True, 'Partei_kurz'] = 'AfD'
data_complete.loc[data_complete['Partei'].str.contains('Tierschutzpartei') == True, 'Partei_kurz'] = 'Tierschutzpartei'
data_complete.loc[data_complete['Partei'].str.contains('Freie Demokra') == True, 'Partei_kurz'] = 'FDP'
data_complete.loc[data_complete['Partei'].str.contains('Sozialdemo') == True, 'Partei_kurz'] = 'SPD'
data_complete.loc[data_complete['Partei'].str.contains('Christlich Demokratische U') == True, 'Partei_kurz'] = 'CDU'
data_complete.loc[data_complete['Partei'].str.contains('Partei fÃ¼r Arbeit') == True, 'Partei_kurz'] = 'Partei'
data_complete.loc[data_complete['Partei'].str.contains('FW') == True, 'Partei_kurz'] = 'Freie WÃ¤hler'
data_complete.loc[data_complete['Partei'].str.contains('REP') == True, 'Partei_kurz'] = 'Rep'
data_complete.loc[data_complete['Partei'].str.contains('PRO NRW') == True, 'Partei_kurz'] = 'Pro NRW'
data_complete.loc[data_complete['Partei'].str.contains('ESSENER BÃœ') == True, 'Partei_kurz'] = 'EBB'
data_complete.loc[data_complete['Partei'].str.contains('WfW') == True, 'Partei_kurz'] = 'WfW'
data_complete.loc[data_complete['Partei'].str.contains('Freie WÃ¤hler') == True, 'Partei_kurz'] = 'Freie WÃ¤hler'
data_complete.loc[data_complete['Partei'].str.contains('NPD') == True, 'Partei_kurz'] = 'NPD'
data_complete.loc[data_complete['Partei'].str.contains('GrÃ¼ne Alt') == True, 'Partei_kurz'] = 'GAL'
data_complete.loc[data_complete['Partei'].str.contains('GAL') == True, 'Partei_kurz'] = 'GAL'
data_complete.loc[data_complete['Partei'].str.contains('UW') == True, 'Partei_kurz'] = 'UW'
data_complete.loc[data_complete['Partei'].str.contains('UnabhÃ¤ngige') == True, 'Partei_kurz'] = 'UW'
data_complete.loc[data_complete['Partei'].str.contains('GrÃ¼ne') == True, 'Partei_kurz'] = 'GrÃ¼ne'
data_complete.loc[data_complete['Partei'].str.contains('Linke') == True, 'Partei_kurz'] = 'Linke'
data_complete.loc[data_complete['Partei'].str.contains('BG') == True, 'Partei_kurz'] = 'BG'
data_complete.loc[data_complete['Partei'].str.contains('BÃ¼rger') == True, 'Partei_kurz'] = 'BG'
data_complete.loc[data_complete['Partei'].str.contains('Ã–DP') == True, 'Partei_kurz'] = 'Ã¶dp'
data_complete.loc[data_complete['Partei'].str.contains('Innovation') == True, 'Partei_kurz'] = 'BIG'
data_complete.loc[data_complete['Partei'].str.contains('BIG') == True, 'Partei_kurz'] = 'BIG'
data_complete.loc[data_complete['Partei'].str.contains('Einzelbewer') == True, 'Partei_kurz'] = 'Einzelbewerber'
data_complete.loc[data_complete['Partei'].str.contains(' 90') == True, 'Partei_kurz'] = 'GrÃ¼ne'
data_complete.loc[data_complete['Partei'].str.contains(' Liberales BÃ¼ndnis Essen') == True, 'Partei_kurz'] = 'SLB'
data_complete.loc[data_complete['Partei'].str.contains('Piraten') == True, 'Partei_kurz'] = 'Piraten'

data_complete['Soziale_liste'] = 0
data_complete.loc[(data_complete['Partei'].str.contains('ozial') == True) & (data_complete['Partei_kurz'] != 'SPD'), 'Soziale_list'] = 1

data_complete['BÃ¼rger_list'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'BG') | (data_complete['Partei_kurz'] == 'UW') | (data_complete['Partei'].str.contains('Christ') == 'True'), 'BÃ¼rger_list'] = 1

data_complete['linke_list'] = 0
data_complete.loc[(data_complete['Partei_kurz'] != 'Linke') & (data_complete['Partei'].str.contains('bunt') == True) | (data_complete['Partei'].str.contains('Christ') == 'Vielfalt'), 'linke_list'] = 1

data_complete['SPD'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'SPD'), 'SPD'] = 1

data_complete['CDU'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'CDU'), 'CDU'] = 1

data_complete['GrÃ¼ne'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'GrÃ¼ne'), 'GrÃ¼ne'] = 1

data_complete['Linke'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'Linke'), 'Linke'] = 1

data_complete['FDP'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'FDP'), 'FDP'] = 1

data_complete['AfD'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'AfD'), 'AfD'] = 1

data_complete['FW'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'FW'), 'FW'] = 1

data_complete['NPD'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'NPD'), 'NPD'] = 1

data_complete['Die_Partei'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'Partei'), 'Die_Partei'] = 1

data_complete['Piraten'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'Piraten'), 'Piraten'] = 1

data_complete['Tierschutz'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'Tierschutz'), 'Tierschutz'] = 1

data_complete['REP'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'REP'), 'REP'] = 1

data_complete['DKP'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'DKP'), 'DKP'] = 1

data_complete['Pro NRW'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'Pro NRW'), 'Pro NRW'] = 1

data_complete['GAL'] = 0
data_complete.loc[(data_complete['Partei_kurz'] == 'GAL'), 'GAL'] = 1

In [8]:
data_manifesto['Jahr'] = data_manifesto['Jahr'].astype(float)
data_complete['Jahr'] = data_complete['Jahr'].astype(float)
data_manifesto['Partei'] = data_manifesto['Partei'].astype(str)
data_complete['Partei'] = data_complete['Partei'].astype(str)
data_manifesto['Partei_kurz'] = data_manifesto['Partei']
data_complete = pd.merge(data_complete, data_manifesto.dropna(), on=["Jahr", "Partei_kurz"], how="left", validate="m:1")
data_complete

,Unnamed: 0,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei_x,Wahlbezirk,Wahlkreis_ID,Plz,...,Proctectionism_neg,equality_pos,culture_pos,nation_life_pos,multiculti_pos,law_order_pos,laborers_pos,farmers_pos,Middle_class,Minorities
0,0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,...,0.000,9.301,3.138,1.512,1.399,5.709,6.352,0.681,0.000,0.000
1,1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,...,0.149,3.651,2.534,6.632,2.459,3.726,4.098,1.937,0.298,0.075
2,2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,...,0.000,13.445,1.161,0.155,3.948,2.323,6.477,0.697,0.000,0.000
3,3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,...,0.000,20.284,1.269,0.000,2.412,0.559,9.139,0.381,0.000,0.000
4,4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43074,43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43075,43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43076,43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43077,43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,...,0.056,9.532,1.895,0.000,2.007,0.167,4.738,0.390,0.000,1.672
43078,43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,...,0.000,8.219,0.000,2.740,1.370,0.000,0.000,0.000,0.000,1.370

In [9]:
col_man = ['Right-Left', 'welfare', 'Military_pos', 'peace', 'EU_pos', 'international_pos', 'EU_neg', 'Free_market', 'Proctectionism_neg', 'equality_pos', 'culture_pos', 'nation_life_pos', 'multiculti_pos', 'law_order_pos', 
           'laborers_pos', 'farmers_pos', 'Middle_class', 'Minorities']

for i in range(len(col_man)):
    
    data_complete.loc[(data_complete['Soziale_list'] == 1) & (data_complete['Jahr'] == 2014.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'SPD') | (data_complete['Partei_kurz'] == 'GrÃ¼ne') | (data_complete['Partei_kurz'] == 'Linke') & (data_complete['Jahr'] == 2014.)][col_man[i]].mean()

    data_complete.loc[(data_complete['Soziale_list'] == 1) & (data_complete['Jahr'] == 2020.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'SPD') | (data_complete['Partei_kurz'] == 'GrÃ¼ne') | (data_complete['Partei_kurz'] == 'Linke') & (data_complete['Jahr'] == 2020.)][col_man[i]].mean()
    
    data_complete.loc[(data_complete['BÃ¼rger_list'] == 1) & (data_complete['Jahr'] == 2014.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'CDU') | (data_complete['Partei_kurz'] == 'FDP')
    & (data_complete['Jahr'] == 2014.) ].mean()                                                                                                                
    
    data_complete.loc[(data_complete['BÃ¼rger_list'] == 1) & (data_complete['Jahr'] == 2020.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'CDU') | (data_complete['Partei_kurz'] == 'FDP')
    & (data_complete['Jahr'] == 2020.) ].mean()
    
    data_complete.loc[(data_complete['linke_list'] == 1) & (data_complete['Jahr'] == 2014.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'Linke') & (data_complete['Jahr'] == 2014.)][col_man[i]].mean()                                                                                                         
    data_complete.loc[(data_complete['linke_list'] == 1) & (data_complete['Jahr'] == 2020.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'Linke') & (data_complete['Jahr'] == 2020.)][col_man[i]].mean()
    
    
    data_complete.loc[(data_complete['GAL'] == 1) & (data_complete['Jahr'] == 2014.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'GrÃ¼ne') | (data_complete['Partei_kurz'] == 'Linke') &
                                                                                                                   (data_complete['Jahr'] == 2014.)][col_man[i]].mean()

    data_complete.loc[(data_complete['GAL'] == 1) & (data_complete['Jahr'] == 2020.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'GrÃ¼ne') | (data_complete['Partei_kurz'] == 'Linke') &
                                                                                                                   (data_complete['Jahr'] == 2020.)][col_man[i]].mean()
    
    data_complete.loc[(data_complete['Die_Partei'] == 1) & (data_complete['Jahr'] == 2014.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'GrÃ¼ne') | (data_complete['Partei_kurz'] == 'Linke') &
                                                                                                                   (data_complete['Jahr'] == 2014.)][col_man[i]].mean()

    data_complete.loc[(data_complete['Die_Partei'] == 1) & (data_complete['Jahr'] == 2020.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'GrÃ¼ne') | (data_complete['Partei_kurz'] == 'Linke') &
                                                                                                                   (data_complete['Jahr'] == 2020.)][col_man[i]].mean()
    
    
    data_complete.loc[(data_complete['Piraten'] == 1) & (data_complete['Jahr'] == 2020.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'Linke') | (data_complete['Partei_kurz'] == 'FDP') &
                                                                                                                   (data_complete['Jahr'] == 2020.)][col_man[i]].mean()
    
    
    data_complete.loc[(data_complete['FW'] == 1) & (data_complete['Jahr'] == 2014.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'SPD') | (data_complete['Partei_kurz'] == 'FDP') | (data_complete['Partei_kurz'] == 'CDU') &
                                                                                                                   (data_complete['Jahr'] == 2014.)][col_man[i]].mean()
    
    data_complete.loc[(data_complete['FW'] == 1) & (data_complete['Jahr'] == 2020.0), col_man[i]] = data_complete[(data_complete['Partei_kurz'] == 'SPD') | (data_complete['Partei_kurz'] == 'FDP') | (data_complete['Partei_kurz'] == 'CDU') &
                                                                                                                   (data_complete['Jahr'] == 2020.)][col_man[i]].mean()
    
    data_complete.loc[(data_complete[col_man[i]].astype(str) == 'nan') & (data_complete['Jahr'] == 2014.), col_man[i]] = data_complete[data_complete['Jahr'] == 2014.][col_man[i]].mean()
    data_complete.loc[(data_complete[col_man[i]].astype(str) == 'nan') & (data_complete['Jahr'] == 2020.), col_man[i]] = data_complete[data_complete['Jahr'] == 2020.][col_man[i]].mean()

In [10]:
data_complete['doctor'] = 0
data_complete.loc[(data_complete['Nachname'].str.contains('Dr.') == True) | (data_complete['Name_total'].str.contains('Dr.') == True), 'doctor'] = 1
data_complete

,Unnamed: 0,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei_x,Wahlbezirk,Wahlkreis_ID,Plz,...,equality_pos,culture_pos,nation_life_pos,multiculti_pos,law_order_pos,laborers_pos,farmers_pos,Middle_class,Minorities,doctor
0,0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,...,9.301000,3.138000,1.512000,1.399000,5.709000,6.352000,0.681000,0.000000,0.000000,0
1,1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,...,3.651000,2.534000,6.632000,2.459000,3.726000,4.098000,1.937000,0.298000,0.075000,0
2,2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,...,13.445000,1.161000,0.155000,3.948000,2.323000,6.477000,0.697000,0.000000,0.000000,0
3,3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,...,20.284000,1.269000,0.000000,2.412000,0.559000,9.139000,0.381000,0.000000,0.000000,0
4,4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,...,9.690303,1.697953,2.512406,2.117869,3.121963,5.979183,0.822840,0.136792,0.065974,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43074,43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,...,7.771251,2.392232,1.279520,1.164949,1.969135,5.216298,0.929018,0.160246,1.066922,0
43075,43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,...,7.771251,2.392232,1.279520,1.164949,1.969135,5.216298,0.929018,0.160246,1.066922,0
43076,43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,...,7.771251,2.392232,1.279520,1.164949,1.969135,5.216298,0.929018,0.160246,1.066922,0
43077,43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,...,9.532000,1.895000,0.000000,2.007000,0.167000,4.738000,0.390000,0.000000,1.672000,0
43078,43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,...,8.219000,0.000000,2.740000,1.370000,0.000000,0.000000,0.000000,0.000000,1.370000,0

In [11]:
data_complete_1 = pd.merge(data_complete, df_controls, on=["Jahr", "Stadt"], how="left")
data_complete_1

,Unnamed: 0,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei_x,Wahlbezirk,Wahlkreis_ID,Plz,...,employees,unemployed_tot,unemployed_foreign,unemployed_youth,unemployed_old,long_time_unemployed,tourist_arrivals,social_sec,filed_bancruptcies_firms,employees_beau
0,0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
1,1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
2,2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
3,3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
4,4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,...,210103,34640,13002,3063,5094,13004,842463,102465.0,136.0,10315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46204,43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,...,114448,19059,5605,1844,2685,8690,218544,54676.0,165.0,6285
46205,43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,...,114448,19059,5605,1844,2685,8690,218544,54676.0,165.0,6285
46206,43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,...,114448,19059,5605,1844,2685,8690,218544,54676.0,165.0,6285
46207,43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,...,114448,19059,5605,1844,2685,8690,218544,54676.0,165.0,6285
46208,43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,...,114448,19059,5605,1844,2685,8690,218544,54676.0,165.0,6285

In [22]:
df_votes = pd.read_csv(r"C:\Users\mariu\Downloads\votes_btw.csv", sep=';', engine='python') # no geo data needed
data_complete_2 = pd.merge(data_complete_1, df_votes, on=["Stadt", "Jahr"], how="left")
data_complete_2

,Unnamed: 0,index,Kandidaten_ID,Name_total,Beruf,Geburtsjahr,Partei_x,Wahlbezirk,Wahlkreis_ID,Plz,...,filed_bancruptcies_firms,employees_beau,Stimmen_CDU,Stimmen_SPD,Stimmen_FDP,Stimmen_AfD,Stimmen_GrÃ¼nen,Stimmen_Linke,Stimmen_Piraten,Stimmen_Rep
0,0,0,1000.0,"GrÃ¶ne, Jens-Peter",Kaufmann,1966.0,Sozialdemokratische Partei Deutschlands (SPD),Stadtmitte,0.0,4513800.0,...,136.0,10315,84119.0,87154.0,38675.0,35155.0,23468.0,25249.0,1298.0,0.0
1,1,1,2000.0,"Moos, Christiane",Bilanzbuchhalterin,1959.0,Christlich Demokratische Union Deutschlands (CDU),Stadtmitte,0.0,4513900.0,...,136.0,10315,84119.0,87154.0,38675.0,35155.0,23468.0,25249.0,1298.0,0.0
2,2,2,3000.0,"Schumacher, Sandra",Orchestermusikerin,1982.0,BÃœNDNIS 90/DIE GRÃœNEN (GRÃœNE),Stadtmitte,0.0,4513100.0,...,136.0,10315,84119.0,87154.0,38675.0,35155.0,23468.0,25249.0,1298.0,0.0
3,3,3,4000.0,"El-Khatib, Jules",Angestellter,1991.0,DIE LINKE (DIE LINKE),Stadtmitte,0.0,4530700.0,...,136.0,10315,84119.0,87154.0,38675.0,35155.0,23468.0,25249.0,1298.0,0.0
4,4,4,5000.0,"Hemsteeg, Kai",Kriminaloberkommissar,1981.0,ESSENER BÃœRGER BÃœNDNIS (EBB) - Freie WÃ¤hler (E...,Stadtmitte,0.0,4513400.0,...,136.0,10315,84119.0,87154.0,38675.0,35155.0,23468.0,25249.0,1298.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46204,43074,42748,NaN,NaN,NaN,NaN,WfW,Ronsdorf West,33.0,NaN,...,165.0,6285,57318.0,54291.0,9827.0,7022.0,16702.0,14013.0,4091.0,468.0
46205,43075,42749,NaN,NaN,NaN,NaN,REP,Ronsdorf West,33.0,NaN,...,165.0,6285,57318.0,54291.0,9827.0,7022.0,16702.0,14013.0,4091.0,468.0
46206,43076,42750,NaN,NaN,NaN,NaN,PRO NRW,Ronsdorf West,33.0,NaN,...,165.0,6285,57318.0,54291.0,9827.0,7022.0,16702.0,14013.0,4091.0,468.0
46207,43077,42751,NaN,NaN,NaN,NaN,PIRATEN,Ronsdorf West,33.0,NaN,...,165.0,6285,57318.0,54291.0,9827.0,7022.0,16702.0,14013.0,4091.0,468.0
46208,43078,42752,NaN,NaN,NaN,NaN,AfD,Ronsdorf West,33.0,NaN,...,165.0,6285,57318.0,54291.0,9827.0,7022.0,16702.0,14013.0,4091.0,468.0

In [23]:
data_complete_2.to_excel(r"C:\Users\mariu\Documents\Project Local Elections\nrw\data_nrw.xlsx")
data_complete_2.to_csv(r"C:\Users\mariu\Documents\Project Local Elections\nrw\data_nrw.csv")

In [ ]:
data_complete.to_excel